-- 费用结算中心：补齐 Preview/生产库缺失的迭代 2/3 结构
-- 在 Supabase Dashboard → SQL Editor 中整段执行即可（可重复执行）
--
-- 已确认线上报错：
-- 1) column CasePerformance.deduction_status does not exist
-- 2) relation "assessment" does not exist

begin;

-- ========== 迭代 2：结算审核扣减字段 + 作业记录 ==========
create table if not exists public.case_work_record (
  id bigserial primary key,
  service_case_id bigint not null unique references public.service_case(id) on delete cascade,
  gsp_case_no varchar(32) not null unique,
  inspector_id uuid not null references public.users(id),
  workload jsonb not null default '{}'::jsonb,
  mileage numeric(12,2) not null default 0,
  expenses numeric(12,2) not null default 0,
  expense_note text,
  mileage_screenshot_urls jsonb not null default '[]'::jsonb,
  work_note text,
  accepted_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_case_work_record_inspector
  on public.case_work_record(inspector_id, updated_at desc);

alter table public.case_performance
  add column if not exists deduction_status varchar(16) not null default 'none',
  add column if not exists deduction_review_by uuid references public.users(id),
  add column if not exists deduction_review_time timestamptz;

create index if not exists idx_service_case_inspector_status
  on public.service_case(inspector_id, status);
create index if not exists idx_case_performance_review
  on public.case_performance(review_status, month);

alter table public.case_work_record enable row level security;

-- ========== 迭代 3：考核 + 月度结算 ==========
create table if not exists public.assessment (
  id bigint generated by default as identity primary key,
  month varchar(7) not null,
  user_id uuid not null references public.users(id),
  user_role varchar(24) not null,
  internal_score numeric(5,2) not null default 0 check (internal_score between 0 and 100),
  sungrow_score numeric(5,2) not null default 0 check (sungrow_score between 0 and 100),
  total_score numeric(5,2) not null default 0,
  rank_group varchar(24) not null check (rank_group in ('station_manager','inspector')),
  rank_result varchar(24),
  reward_amount numeric(12,2) not null default 0,
  tool_subsidy numeric(12,2) not null default 0,
  other_subsidy numeric(12,2) not null default 0,
  subsidy_remark text,
  correction_amount numeric(12,2) not null default 0,
  correction_reason text,
  updated_by uuid references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(month, user_id)
);

create table if not exists public.monthly_settlement (
  id bigint generated by default as identity primary key,
  month varchar(7) not null,
  user_id uuid not null references public.users(id),
  perf_total numeric(12,2) not null default 0,
  reward_total numeric(12,2) not null default 0,
  subsidy_total numeric(12,2) not null default 0,
  correction_total numeric(12,2) not null default 0,
  final_amount numeric(12,2) not null default 0,
  status varchar(16) not null default 'draft' check (status in ('draft','corrected','locked')),
  locked_by uuid references public.users(id),
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(month, user_id)
);

create index if not exists idx_assessment_month on public.assessment(month);
create index if not exists idx_monthly_settlement_month on public.monthly_settlement(month);

-- ========== 条目价格映射（PO 确认入库依赖） ==========
create table if not exists public.item_price_mapping (
  id bigint generated by default as identity primary key,
  source_item_name varchar(255) not null unique,
  normalized_source varchar(255) not null,
  target_item_code varchar(255) not null,
  mapping_type varchar(16) not null default 'manual'
    check (mapping_type in ('manual', 'builtin')),
  confidence numeric(5,4) not null default 1,
  status varchar(16) not null default 'active'
    check (status in ('active', 'inactive')),
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_item_price_mapping_normalized
  on public.item_price_mapping(normalized_source);
create index if not exists idx_item_price_mapping_target
  on public.item_price_mapping(target_item_code);

alter table public.po_item
  drop constraint if exists po_item_price_status_check;

alter table public.po_item
  add constraint po_item_price_status_check
  check (price_status in ('ok', 'pending_price', 'ignored'));

-- 综合工时条目编码很长，varchar(255) 会导致价格导入 500
alter table public.price_library
  alter column item_code type text,
  alter column item_name type text;

commit;

-- 执行后可自检：
-- select column_name from information_schema.columns where table_name='case_performance' and column_name='deduction_status';
-- select to_regclass('public.assessment'), to_regclass('public.monthly_settlement');
