-- 费用结算：补齐 PO 导入依赖的条目映射表（以及价格状态约束）
-- 在 Supabase SQL Editor 整段执行即可
--
-- 已确认线上报错：
-- relation "item_price_mapping" does not exist
-- （PO「确认入库」会先读这张表，所以预览成功、入库失败）

begin;

create table if not exists public.item_price_mapping (
  id bigint generated by default as identity primary key,
  source_item_name varchar(255) not null unique,
  normalized_source varchar(255) not null,
  target_item_code varchar(255) not null,
  mapping_type varchar(16) not null default 'manual'
    check (mapping_type in ('manual', 'builtin')),
  confidence numeric(5,4) not null default 1,
  status varchar(16) not null default 'active'
    check (status in ('active', 'inactive')),
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_item_price_mapping_normalized
  on public.item_price_mapping(normalized_source);
create index if not exists idx_item_price_mapping_target
  on public.item_price_mapping(target_item_code);

-- 允许通用条目被标记为 ignored
alter table public.po_item
  drop constraint if exists po_item_price_status_check;

alter table public.po_item
  add constraint po_item_price_status_check
  check (price_status in ('ok', 'pending_price', 'ignored'));

commit;

-- 自检：
-- select to_regclass('public.item_price_mapping');
