-- 月度考核：专业指标事件扣罚 + 事件扣罚汇总字段
-- 在 Supabase SQL Editor 执行（可重复执行）

begin;

create table if not exists public.assessment_event (
  id bigint generated by default as identity primary key,
  month varchar(7) not null,
  user_id uuid not null references public.users(id) on delete cascade,
  category varchar(64) not null,
  content text not null,
  unit varchar(16) not null default '次',
  qty numeric(12,2) not null default 1,
  unit_amount numeric(12,2),
  amount numeric(12,2) not null default 0,
  remark text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_assessment_event_month_user
  on public.assessment_event(month, user_id);

alter table public.assessment
  add column if not exists event_penalty numeric(12,2) not null default 0;

alter table public.monthly_settlement
  add column if not exists event_penalty numeric(12,2) not null default 0;

commit;
