begin;

create table if not exists public.assessment (
  id bigint generated by default as identity primary key,
  month varchar(7) not null,
  user_id uuid not null references public.users(id),
  user_role varchar(24) not null,
  internal_score numeric(5,2) not null default 0 check (internal_score between 0 and 100),
  sungrow_score numeric(5,2) not null default 0 check (sungrow_score between 0 and 100),
  total_score numeric(5,2) not null default 0,
  rank_group varchar(24) not null check (rank_group in ('station_manager','inspector')),
  rank_result varchar(24),
  reward_amount numeric(12,2) not null default 0,
  tool_subsidy numeric(12,2) not null default 0,
  other_subsidy numeric(12,2) not null default 0,
  subsidy_remark text,
  correction_amount numeric(12,2) not null default 0,
  correction_reason text,
  updated_by uuid references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(month, user_id)
);

create table if not exists public.monthly_settlement (
  id bigint generated by default as identity primary key,
  month varchar(7) not null,
  user_id uuid not null references public.users(id),
  perf_total numeric(12,2) not null default 0,
  reward_total numeric(12,2) not null default 0,
  subsidy_total numeric(12,2) not null default 0,
  correction_total numeric(12,2) not null default 0,
  final_amount numeric(12,2) not null default 0,
  status varchar(16) not null default 'draft' check (status in ('draft','corrected','locked')),
  locked_by uuid references public.users(id),
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(month, user_id)
);

create index if not exists idx_assessment_month on public.assessment(month);
create index if not exists idx_monthly_settlement_month on public.monthly_settlement(month);
commit;
