-- 费用结算中心迭代 1 补充：PO 条目到价格库编码的可维护映射。
create table if not exists public.item_price_mapping (
  id bigint generated by default as identity primary key,
  source_item_name varchar(255) not null unique,
  normalized_source varchar(255) not null,
  target_item_code varchar(255) not null,
  mapping_type varchar(16) not null default 'manual'
    check (mapping_type in ('manual', 'builtin')),
  confidence numeric(5,4) not null default 1,
  status varchar(16) not null default 'active'
    check (status in ('active', 'inactive')),
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_item_price_mapping_normalized
  on public.item_price_mapping(normalized_source);
create index if not exists idx_item_price_mapping_target
  on public.item_price_mapping(target_item_code);
