-- 费用结算中心：迭代 1。
-- 金额统一 numeric(12,2)，新表与既有巡检表解耦。

alter table public.users add column if not exists region varchar(16);
alter table public.users add column if not exists org_unit varchar(64);

create table if not exists public.import_batch (
  id bigint generated by default as identity primary key,
  import_type varchar(32) not null check (import_type in ('gsp_case', 'po_order', 'settle_price')),
  file_name varchar(255) not null,
  total_rows integer not null default 0,
  success_rows integer not null default 0,
  fail_rows integer not null default 0,
  fail_detail jsonb not null default '[]'::jsonb,
  operator_id uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_case (
  id bigint generated by default as identity primary key,
  gsp_case_no varchar(32) not null unique,
  project_name varchar(128) not null,
  service_type varchar(32),
  creator varchar(32),
  province varchar(16),
  city varchar(32),
  site_desc text,
  region varchar(16) not null default 'south_china' check (region in ('south_china', 'yunnan')),
  status varchar(20) not null default 'pending_assign' check (status in ('pending_assign','assigned','working','finished','settle_review','settled','month_locked')),
  inspector_id uuid references public.users(id) on delete set null,
  assign_by uuid references public.users(id) on delete set null,
  assign_time timestamptz,
  finish_time timestamptz,
  import_batch_id bigint references public.import_batch(id) on delete set null,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_service_case_region on public.service_case(region);
create index if not exists idx_service_case_status on public.service_case(status);
create index if not exists idx_service_case_project on public.service_case(project_name);

create table if not exists public.po_order (
  id bigint generated by default as identity primary key,
  po_no varchar(64) not null unique,
  gsp_case_no varchar(32) not null,
  service_case_id bigint references public.service_case(id) on delete set null,
  po_total_amount numeric(12,2) not null default 0,
  demand_date date,
  demander varchar(64),
  demand_type varchar(32),
  product_line varchar(64),
  product_model varchar(64),
  product_qty numeric(12,2),
  fault_phenomenon text,
  fault_level varchar(64),
  duration_req varchar(64),
  demand_desc text,
  project_area varchar(64),
  project_country varchar(32),
  project_region varchar(64),
  province varchar(16),
  project_name varchar(128),
  project_scene varchar(32),
  submitter varchar(64),
  dingtalk_created_at timestamptz,
  dingtalk_updated_at timestamptz,
  match_status varchar(16) not null default 'pending' check (match_status in ('matched','pending')),
  import_batch_id bigint references public.import_batch(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_po_order_case on public.po_order(gsp_case_no);
create index if not exists idx_po_order_match on public.po_order(match_status);
create index if not exists idx_po_order_demand_date on public.po_order(demand_date);

create table if not exists public.price_library (
  id bigint generated by default as identity primary key,
  price_type varchar(16) not null check (price_type in ('settle','perf')),
  item_code varchar(255) not null,
  item_name varchar(255) not null,
  item_desc text,
  unit varchar(32),
  product_model varchar(64),
  scene varchar(32),
  region varchar(16),
  coop_type varchar(16),
  work_hours numeric(12,2),
  unit_price numeric(12,2) not null,
  effective_date date not null default current_date,
  status varchar(16) not null default 'active' check (status in ('active','inactive')),
  created_by uuid references public.users(id) on delete set null,
  change_remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_price_dimension unique nulls not distinct
    (price_type, item_code, product_model, scene, region, coop_type, effective_date)
);

create index if not exists idx_price_lookup on public.price_library(price_type, item_code, status, effective_date desc);

create table if not exists public.po_item (
  id bigint generated by default as identity primary key,
  po_id bigint not null references public.po_order(id) on delete cascade,
  source_row integer,
  item_category varchar(16) not null check (item_category in ('special','general')),
  item_code varchar(255) not null,
  item_name varchar(255) not null,
  item_desc text,
  unit varchar(32),
  qty numeric(12,2) not null default 0,
  settle_price numeric(12,2),
  perf_price numeric(12,2),
  item_revenue numeric(12,2) not null default 0,
  item_perf numeric(12,2) not null default 0,
  price_status varchar(20) not null default 'pending_price' check (price_status in ('ok','pending_price')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_po_item_po on public.po_item(po_id);
create index if not exists idx_po_item_price_status on public.po_item(price_status);

create table if not exists public.case_performance (
  id bigint generated by default as identity primary key,
  service_case_id bigint not null unique references public.service_case(id) on delete cascade,
  gsp_case_no varchar(32) not null unique,
  inspector_id uuid references public.users(id) on delete set null,
  perf_base numeric(12,2) not null default 0,
  deduction numeric(12,2) not null default 0,
  deduction_reason text,
  deduct_by uuid references public.users(id) on delete set null,
  perf_final numeric(12,2) not null default 0,
  case_revenue numeric(12,2) not null default 0,
  review_status varchar(16) not null default 'pending' check (review_status in ('pending','approved','rejected')),
  reviewer_id uuid references public.users(id) on delete set null,
  review_time timestamptz,
  review_comment text,
  month varchar(7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_case_performance_month on public.case_performance(month);

create table if not exists public.change_log (
  id bigint generated by default as identity primary key,
  entity_type varchar(32) not null,
  entity_id varchar(64) not null,
  field varchar(64) not null,
  old_value text,
  new_value text,
  operator_id uuid references public.users(id) on delete set null,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_change_log_entity on public.change_log(entity_type, entity_id, created_at desc);

